version: '3'
services:
  canary:
    build:
      context: .
      dockerfile: Dockerfile_perception
    ports:
     - "5001:5001"
  model:
    build:
      context: .
      dockerfile: Dockerfile_decision
    ports:
     - "5002:5002"
  elector:
    build:
      context: .
      dockerfile: Dockerfile_navigation
    ports:
     - "5003:5003"

# sudo docker-compose up